UI: Save button functionality added BACKEND: Snippets saved into db
Ravina-Deogadkar/snippet-library pull request #19
Opened 2023-10-15 15:47 UTC by dlrklc

**Some Notes:** 

**1.**  This selection does not work so I commented out this part for my validator implementation. It needs fix fyi.
![ui error](https://github.com/Ravina-Deogadkar/snippet-library/assets/89346619/4d512dd9-b78b-4278-92e0-2250ee5c524f)

**2.**  `const {REACT_APP_SERVER_URL} = process.env;` does not work,  it cannot fetch env variables. Therefore, I added REACT_APP_SERVER_URL as "http://localhost:8181" to Popup.js.

I've finished the implementation. Please let me know if anything is missing.

2023-10-16 09:47 UTC, Ravina-Deogadkar commented
> **Some Notes:**
> 
> **1.** This selection does not work so I commented out this part for my validator implementation. It needs fix fyi. ![ui error](https://user-images.githubusercontent.com/89346619/275336905-4d512dd9-b78b-4278-92e0-2250ee5c524f.png)
> 
> **2.** `const {REACT_APP_SERVER_URL} = process.env;` does not work, it cannot fetch env variables. Therefore, I added REACT_APP_SERVER_URL as "http://localhost:8181" to Popup.js.
> 
> I've finished the implementation. Please let me know if anything is missing.

Did you set REACT_APP_SERVER_URL in .env file?

Don't worry about drop down I'll create another ticket for it.

2023-10-16 09:52 UTC, Ravina-Deogadkar commented on src/component/Popup.js
> +    const title = document.getElementById('outlined-basic').value;
Please use some specific class name for eg:- snippet-title, snippet-code, snippet-tag or sl-title

2023-10-16 09:53 UTC, Ravina-Deogadkar requested changes
Please fix the changes

2023-10-16 11:55 UTC, dlrklc commented
> Please fix the changes

I have updated the var names

2025-03-28 12:46 UTC, closed without merging

2025-03-28 12:58 UTC, dlrklc commented
Closed because repo owner did not give feedback since Oct 16, 2023